name: POI API (.net core)

on:
  push:
    paths:
      - 'apis/poi/**'
  pull_request:
    paths:
      - 'apis/poi/**'
    branches: [ master ]

jobs:
  build_poi:
    name: Build POI API 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.104
    - name: Install dependencies
      run: dotnet restore 'apis/poi/poi.sln'
    - name: Build
      run: dotnet build 'apis/poi/poi.sln' --configuration Release --no-restore
    - name: Test
      run: dotnet test 'apis/poi/tests/UnitTests/UnitTests.csproj' --no-restore --verbosity normal
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "poi.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
