name: Trips API - Monitor

on:
  workflow_run:
    workflows: ["Trips API (go)"]
    branches: [master]
jobs:
  debug:
    name: Run Script 
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ github }}"