name: Trips API (go)

on:
  push:
    paths:
      - 'apis/trips/**'
      - '.github/workflows/trips.yml'
      - '.github/workflows/trips-monitor.yml'
  pull_request:
    paths:
      - 'apis/trips/**'
      - '.github/workflows/trips.yml'
      - '.github/workflows/trips-monitor.yml'
    branches: [ master ]
env:
  ACR_NAME: openhackarw7awr1acr.azurecr.io
  ACR_USER: openhackarw7awr1acr
  IMAGE_NAME: devopsoh/api-trips 
  IMAGE_TAG: ${{ github.run_id }}
  APP_NAME: openhackarw7awr1trips
  RG_NAME: openhackarw7awr1rg
  PRODUCTION_URI: "https://$APP_NAME.azurewebsites.net/api/healthcheck/trips"
  STAGING_URI: "https://$APP_NAME-staging.azurewebsites.net/api/healthcheck/trips"

jobs:
  build_trips:
    name: Build Trips API 
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./apis/trips/...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build
      working-directory: apis/trips
    - name: Test
      run: go test
      working-directory: apis/trips/tests
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "trips.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
  push_to_acr:
    name: Build Docker Image and push to ACR
    needs: build_trips
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and Tag Docker Image
        run: | 
          docker build . -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
        working-directory: apis/trips
      - name: Login to ACR 
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run:  docker login $ACR_NAME -u $ACR_USER -p ${{ secrets.ACR_PASSWORD }} 
      - name: Push to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Failed-Run
        uses: stefanstranger/azuredevops-bug-action@v1
        if: failure()
        with:
            OrganizationName: "mafortun"
            PAT: "PAT"
            ProjectName: "openhack-devopsv2"
            AreaPath: "openhack-devopsv2"
            IterationPath: "openhack-devopsv2\\Iteration 1"
            GithubToken: "GithubToken"
            WorkflowFileName: "trips.yml"
        env:
          PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
          GithubToken: ${{ secrets.GIT_PAT}}
  deploy_to_webapp:
    name: Deploy to WebApp
    needs: push_to_acr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          app-name: 'openhackarw7awr1trips'
          images: "openhackarw7awr1acr.azurecr.io/devopsoh/api-trips:${{ github.run_id }}"
          slot-name: "staging"
      - name: Restart Staging Slot
        run: az webapp restart -n $APP_NAME -g $RG_NAME -s staging
      - run: sleep 60
        name: Sleep for a minute to allow container time to spin up
      - run: sh -c '[ $(curl -o -I -L -s -w "%{http_code}" https://openhackarw7awr1trips-staging.azurewebsites.net/api/healthcheck/trips) -eq 200 ]'
        name: "Run a Healthcheck"
      - name: Swap Staging and Production
        run: az webapp deployment slot swap -n $APP_NAME -g $RG_NAME -s staging --target-slot production
      - name: Failed-Run
        uses: stefanstranger/azuredevops-bug-action@v1
        if: failure()
        with:
            OrganizationName: "mafortun"
            PAT: "PAT"
            ProjectName: "openhack-devopsv2"
            AreaPath: "openhack-devopsv2"
            IterationPath: "openhack-devopsv2\\Iteration 1"
            GithubToken: "GithubToken"
            WorkflowFileName: "trips.yml"
        env:
          PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
          GithubToken: ${{ secrets.GIT_PAT}}
