name: Trips API (go)

on:
  push:
    paths:
      - 'apis/trips/**'
      - '.github/workflows/trips.yml'
  pull_request:
    paths:
      - 'apis/trips/**'
      - '.github/workflows/trips.yml'
    branches: [ master ]
env:
  ACR_NAME: openhackarw7awr1acr.azurecr.io
  ACR_USER: openhackarw7awr1acr
  IMAGE_NAME: devopsoh/api-trips 
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build_trips:
    name: Build Trips API 
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./apis/trips/...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build
      working-directory: apis/trips
    - name: Test
      run: go test
      working-directory: apis/trips/tests
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "trips.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
  push_to_acr:
    name: Build Docker Image and push to ACR
    needs: build_trips
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Tag Docker Image
        run: | 
          docker build . -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
        working-directory: apis/trips
      - name: Login to ACR 
        if: github.event_name == 'push' && github.refs == 'refs/heads/master'
        run:  docker login $ACR_NAME -u $ACR_USER -p ${{ secrets.ACR_PASSWORD }} 
      - name: Push to ACR
        if: github.event_name == 'push' && github.refs == 'refs/heads/master'
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Failed-Run
        uses: stefanstranger/azuredevops-bug-action@v1
        if: failure()
        with:
            OrganizationName: "mafortun"
            PAT: "PAT"
            ProjectName: "openhack-devopsv2"
            AreaPath: "openhack-devopsv2"
            IterationPath: "openhack-devopsv2\\Iteration 1"
            GithubToken: "GithubToken"
            WorkflowFileName: "trips.yml"
        env:
          PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
          GithubToken: ${{ secrets.GIT_PAT}}
