name: Trips API (go)

on:
  push:
    paths:
      - 'apis/trips/**'
  pull_request:
    paths:
      - 'apis/trips/**'
    branches: [ master ]

jobs:
  build_trips:
    name: Build Trips API 
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./apis/trips/...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build
      working-directory: apis/trips
    - name: Test
      run: go test
      working-directory: apis/trips/tests
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "trips.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
