name: Trips API - Swap slots

# on:
#   workflow_run:
#     workflows: ["Trips API - Monitor Staging"]
#     branches: [master]
#     types:
#       - completed
    
jobs:
  debug:
    name: Run Script 
    runs-on: ubuntu-latest
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Swap Staging and Production
      run: az webapp deployment slot swap -n openhackarw7awr1trips -g openhackarw7awr1rg -s staging --target-slot production
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "trips-swap-slot.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}


