name: Trips API - Monitor Staging

# # NO LONGER USED
# on:
#   workflow_run:
#     workflows: ["Trips API (go)"]
#     branches: [master]
#     types:
#       - completed
    
jobs:
  debug:
    name: Run Script 
    runs-on: ubuntu-latest
    steps:
    - run: sleep 60
    - run: sh -c '[ $(curl -o -I -L -s -w "%{http_code}" $URI) -eq 200 ]'
      env: 
        URI: https://openhackarw7awr1trips-staging.azurewebsites.net/api/healthcheck/trips
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "trips-monitor.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}


