name: UserProfile API (Node)

on:
  push:
    paths:
      - 'apis/userprofile/**'
  pull_request:
    paths:
      - 'apis/userprofile/**'
    branches: [ master ]

jobs:
  build_userprofile:
    name: Build UserProfile API 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci 
      name: run npm ci
      working-directory: /apis/userprofile     
    - run: npm run build --if-present
      name: run npm build
      working-directory: /apis/userprofile  
    - run: npm test
      name: run npm test
      working-directory: /apis/userprofile  
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "user-java.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
