name: User-Java API (Java Maven)

on:
  push:
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/user-java.yml'
  pull_request:
    paths:
      - 'apis/user-java/**'
      - '.github/workflows/user-java.yml'
    branches: [ master ]
env:
  ACR_NAME: openhackarw7awr1acr.azurecr.io
  ACR_USER: openhackarw7awr1acr
  IMAGE_NAME: devopsoh/api-user-java
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build_user_java:
    name: Build User-Java API 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file apis/user-java/pom.xml
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "user-java.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
  push_to_acr:
    name: Build Docker Image and push to ACR
    needs: build_user_java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Tag Docker Image
        run: | 
          docker build . -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
        working-directory: apis/user-java
      - name: Login to ACR 
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run:  docker login $ACR_NAME -u $ACR_USER -p ${{ secrets.ACR_PASSWORD }} 
      - name: Push to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Failed-Run
        uses: stefanstranger/azuredevops-bug-action@v1
        if: failure()
        with:
            OrganizationName: "mafortun"
            PAT: "PAT"
            ProjectName: "openhack-devopsv2"
            AreaPath: "openhack-devopsv2"
            IterationPath: "openhack-devopsv2\\Iteration 1"
            GithubToken: "GithubToken"
            WorkflowFileName: "user-java.yml"
        env:
          PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
          GithubToken: ${{ secrets.GIT_PAT}}
