name: UserProfile API (Node)

on:
  push:
    paths:
      - 'apis/userprofile/**'
      - '.github/workflows/userprofile.yml'
  pull_request:
    paths:
      - 'apis/userprofile/**'
      - '.github/workflows/userprofile.yml'
    branches: [ master ]
env:
  ACR_NAME: openhackarw7awr1acr.azurecr.io
  ACR_USER: openhackarw7awr1acr
  IMAGE_NAME: devopsoh/api-userprofile 
  IMAGE_TAG: ${{ github.run_id }}

jobs:
  build_userprofile:
    name: Build UserProfile API 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci 
      name: run npm ci
      working-directory: ./apis/userprofile/    
    - run: npm run build --if-present
      name: run npm build
      working-directory: ./apis/userprofile/ 
    - run: npm test
      name: run npm test
      working-directory: ./apis/userprofile/
    - name: Failed-Run
      uses: stefanstranger/azuredevops-bug-action@v1
      if: failure()
      with:
          OrganizationName: "mafortun"
          PAT: "PAT"
          ProjectName: "openhack-devopsv2"
          AreaPath: "openhack-devopsv2"
          IterationPath: "openhack-devopsv2\\Iteration 1"
          GithubToken: "GithubToken"
          WorkflowFileName: "userprofile.yml"
      env:
        PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
        GithubToken: ${{ secrets.GIT_PAT}}
  push_to_acr:
    name: Build Docker Image and push to ACR
    needs: build_userprofile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{github.ref}}
      - name: Build and Tag Docker Image
        run: | 
          docker build . -t $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
        working-directory: apis/userprofile
      - name: Login to ACR 
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run:  docker login $ACR_NAME -u $ACR_USER -p ${{ secrets.ACR_PASSWORD }} 
      - name: Push to ACR
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker push $ACR_NAME/$IMAGE_NAME:$IMAGE_TAG
      - name: Failed-Run
        uses: stefanstranger/azuredevops-bug-action@v1
        if: failure()
        with:
            OrganizationName: "mafortun"
            PAT: "PAT"
            ProjectName: "openhack-devopsv2"
            AreaPath: "openhack-devopsv2"
            IterationPath: "openhack-devopsv2\\Iteration 1"
            GithubToken: "GithubToken"
            WorkflowFileName: "userprofile.yml"
        env:
          PAT: ${{ secrets.AZURE_DEVOPS_TOKEN}}
          GithubToken: ${{ secrets.GIT_PAT}}
